name: genngxiCF

on:
  # push:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 6 

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # 指定Python版本为3.8

      - name: Install setuptools
        run: |
          pip install --upgrade pip  # 升级pip
          pip install setuptools    # 安装setuptools

      - name: Install dependencies
        run: |
          pip install lxml  # 根据需要安装lxml
          pip install requests      # 安装requests库
          pip install fake_useragent      # 安装requests库
          
      - name: Run Fission.py
        run: python ${{ github.workspace }}/Fission.py



      # 根据需要取消注释以下行
      # - name: Run gengxinhunanip
      #   run: python ${{ github.workspace }}/gengxinhunanip.py

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git add *.txt
            git commit -m "Automatic update"
            git push
          else
            echo "No changes detected, skipping commit."
          fi
